def retirementPlanning():
    return (a,b,c)
def carLoanEMICalc():
    return (a,b,c)
def homeLoanEMICalc():
    return (a,b,c)
def inHandSalCalc():
    return (a,b,c)
def buyHouseTarget():
    return (a,b,c)
def buyCarTarget():
    return (a,b,c)
